name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v4

      - name: read version
        id: read_version
        uses: Saionaro/extract-package-version@v1.2.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/matse_calendar_frontend:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/matse_calendar_frontend:${{ steps.read_version.outputs.version }}, ${{ secrets.DOCKER_HUB_USERNAME }}/matse_calendar_frontend:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
